# Generated by Django 5.2.1 on 2025-10-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="available",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default=1, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[("free", "free"), ("occupied", "occupied")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
